Feature/api-platorm/params (#20)

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -2,27 +2,30 @@ name: Full CI process for Symfony 5 / React
 
 on: [push]
 
+
+
 jobs:
 
   backend :
     name: Running functional and unit test
     runs-on: ubuntu-20.04
-    services:
-      mysql:
-        image: mysql:5.7
-        env:
-          MYSQL_ALLOW_EMPTY_PASSWORD: false
-          MYSQL_ROOT_PASSWORD: symfony
-          MYSQL_DATABASE: symfony
-        ports:
-          - 3306/tcp
-        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
+
     strategy:
       fail-fast: true
       matrix:
-        php-versions: ['7.4-apache','8']
+        php-versions: ['8']
+
+    env: 
+      DB_DATABASE: test_db
+      DB_USER: root
+      DB_PASSWORD: root
+      DB_HOST: 127.0.0.1 
+      APP_ENV: test
+
+   
 
     steps: 
+ 
       # —— Setup Github actions 🐙 —————————————————————————————————————————————
       ## https://github.com/actions/checkout (official)
         - name: Checkout
@@ -66,12 +69,45 @@ jobs:
         - name: Install Composer dependencies
           run: composer install --no-progress --prefer-dist --optimize-autoloader
 
-        - run: composer require symfony/runtime 
-
+       
+      
         ## —— Symfony 🎵 ——————————————————————————————————————————————————————————
     
         - name: Check Symfony requirements
           run: vendor/bin/requirements-checker
+
+           ## —— Setup MySql ——————————————————————————————————————————————————————————
+    
+        - name: Set up MySQL
+          run: |
+            sudo /etc/init.d/mysql start
+            mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS db1;'
+            mysql -e 'CREATE DATABASE IF NOT EXISTS ${{env.DB_DATABASE }};' -u${{env.DB_USER }} -p${{ env.DB_PASSWORD }}
+            mysql -e 'CREATE DATABASE IF NOT EXISTS ${{env.DB_DATABASE }}_${{env.APP_ENV}};' -u${{env.DB_USER }} -p${{ env.DB_PASSWORD }}
+            mysql -e 'status ;' -u${{env.DB_USER }} -p${{ env.DB_PASSWORD }}
+            mysql -e 'SHOW VARIABLES ;' -u${{env.DB_USER}} -p${{env.DB_PASSWORD}}
+            mysql -e 'SHOW DATABASES;' -u${{env.DB_USER}} -p${{env.DB_PASSWORD}}
+      
+        ## —— Unit Tests🎵 ——————————————————————————————————————————————————————————
+    
+        - name: php-unit
+          run: vendor/bin/phpunit --testdox
+
+  
+      ## run tests
+
+        - name: Run Migration && Load Fixtures
+          env:
+            APP_ENV: test
+            MYSQL_ROOT_PASSWORD: ${{env.DB_PASSWORD}}
+            MYSQL_DATABASE: ${{env.DB_DATABASE}}
+            DB_PORT: 3306
+            DATABASE_URL: mysql://${{env.DB_USER}}:${{env.DB_PASSWORD}}@127.0.0.1:3306/${{env.DB_DATABASE}}
+          run: |
+            php bin/console doctrine:schema:drop --force
+            php bin/console doctrine:schema:update --env=test --force || echo "No migrations found or schema update failed"
+            php bin/console doctrine:fixtures:load --no-interaction
+         
 
         ## —— JWT 💫 —————————————————————————————————————————————————————————————
         - name: Generate the SSL keys
@@ -89,4 +125,6 @@ jobs:
 
         - name: npm run build
           run: npm run build
+
+     
 
